# Generated by Django 5.2.6 on 2025-09-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=50)),
                ('design', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('cate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
